nakjun12/seo-blog

- app/(posts)/posts/[...slug]/layout.tsx
1. post 페이지 layout 추가
- post 페이지 좌우 layout 추가
> feat: post 페이지 layout 추가

- app/layout.tsx
- src/app/google-addon.tsx
- src/app/noscript-tagmanager.tsx
- src/shared/config/constant.ts
google addon 추가
GA4, GTM, ADSense 추가하기 위하여 넣었습니다.
app 폴더 google-addon, noscript-tagmanager 컴포넌트 추가 및 적용
아래 내용에 근거하여 pageView 관련하여 컴포넌트 만들었다가 삭제하였음
https://support.google.com/analytics/answer/9234069?hl=ko
> Feature/google addon 추가

- app/(posts)/[slug]/page.tsx
- src/_pages/home/home.page.tsx
1. category 링크 수정
- category 페이지에서 게시글 링크를 불러오는 로직에서 includes 사용으로 인해 링크가 변경되서 수정
- category 페이지 게시글 분배 로직 수정
> fix: category 링크 수정

- posts/next/nextjs-env.mdx
- tailwind.config.ts
1. tailwind config esm으로 통일
- tailwind config의 import 방식이 esm, cjs 가 혼동되어 있어 수정
- tailwind config esm으로 통일
> config: tailwind config esm으로 통일

- app/(posts)/posts/[...slug]/page.tsx
- src/entities/posts/lib/utils/post.util.ts
- src/entities/posts/model/post.ts
- src/entities/posts/ui/post-author-foot.tsx
- src/entities/posts/ui/post-author-head.tsx
- src/shared/common-ui/breadcrumb/breadcrumb.tsx
- src/shared/common-ui/mdx/next-image.tsx
- src/shared/common-ui/mdx/next-link.tsx
- src/shared/config/constant.ts
1. BASE_URL 수정
2. authorIcon title 설정
3. breadcrumb 현재 위치 링크로 변경
4. author 컴포넌트 글씨색 수정
5. posts 경로용 CreatePostUrl 유틸 함수 추가
6. mdx 이미지, 링크에 타이틀 추가
- 도메인 구매로 인한 배포 URL 변경
- authorIcon title 부재
- 현재 위치도 링크로 수정
- 라이트하우스 접근성 항목에 부적합 판정
- posts 경로는 url에 추가적으로 posts가 붙음
- mdx 이미지, 링크에 title 부재
> fix: small fixesBASE_URL 수정

- app/layout.tsx
- src/shared/common-ui/progress-bar/progress-bar.tsx
- src/widgets/header/header.tsx
> feat: header 추가

- src/widgets/header/header.tsx
1. progress bar header에 추가
- 변경 사항 1
- 변경 사항 2
- ...
> feat: progress bar header에 추가

- app/(posts)/posts/[slug]/page.tsx
- app/(posts)/posts/page.tsx
- app/layout.tsx
- src/entities/posts/lib/utils/post.util.ts
1. posts 메타데이터 추가
2. 메인 페이지 메타데이터 임시 작성
> feat: posts 메타데이터 추가

- app/layout.tsx
- src/widgets/footer/footer.tsx
1. feat: footer 추가
- feat: footer 추가
> feat: footer 추가

- src/feature/open-menu/index.ts
- src/feature/open-menu/open-menu.tsx
- src/shared/common-ui/progress-bar/progress-bar.tsx
- src/widgets/header/header.tsx
- 프로그레스바 폭을 조정
- 햄버거 버튼 구현
- 단순 열고 닫는 애니메이션만 추가
- 메뉴와 연결된 아이콘이라 어디에 구현해야할지 고민하다 `feature/open-menu` 에 open-menu.tsx에 구현, Header에 import 해둠
- 데스크탑 반응형시 hidden 필요
> [feat] 햄버거 버튼 구현 & 프로그레스바 폭 수정

- src/_pages/post/post.page.tsx
- src/feature/desktop-category/desktop-category.tsx
- src/shared/common-ui/breadcrumb/breadcrumb.tsx
- src/widgets/footer/footer.tsx
1. Breadcrumb의 현재 위치 link => p 수정
2. post 페이지의 breadcrumb 현재위치 파일 제목 => 글 제목 수정
> [fix] breadcrumb 수정

- posts/react/css-library-comparison.mdx
> [fix] CSS 라이브러리 글 수정

- app/(posts)/[...slug]/layout.tsx
- pnpm-lock.yaml
- src/_pages/post/post.page.tsx
- src/entities/posts/lib/utils/time.util.ts
- src/entities/posts/lib/utils/toc.util.ts
- src/entities/posts/model/post.ts
- src/entities/posts/ui/post-author-head.tsx
- src/feature/desktop-category/desktop-category.tsx
- src/feature/mobile-category/mobile-category.tsx
- src/feature/open-category/open-category.tsx
- src/feature/open-menu/open-menu.tsx
- src/shared/stores/toggle-menu.ts
- src/widgets/header/header.tsx
1. [remove] toc util console.log 제거
2. [fix] post 로드 함수 최신순 정렬로 수정
3. [fix] desktop 카테고리 스크롤 블락 이슈 수정
4. [fix] post 페이지 padding 중복 적용 문제 수정
- 테스트용 console.log 제거
- posts를 가져오는 함수들에 최신순 정렬 적용
- 모바일 카테고리에서의 스크롤 블락이 데스크탑 카테고리에서도 적용되던 이슈
- 모바일과 데스크탑의 메뉴 state를 분리하여 해결
- post layout과 category layout에서 padding이 중복 적용
- post layout의 padding 제거
> [fix] 여러가지 이슈 수정

- src/_pages/post/post.page.tsx
- src/entities/posts/ui/post-author-head.tsx
- src/entities/posts/ui/post-card.tsx
- src/entities/posts/ui/post-title-image.tsx
- src/shared/common-ui/mdx/mdx-remote.tsx
> [feat] post title image 추가

- src/_pages/home/home.page.tsx
- src/entities/posts/ui/recommend-post.tsx
- src/shared/common-ui/toc/toc.tsx
- tailwind.config.ts
> [feat] home 페이지 추천글 추가

- posts/react/css-library-comparison.mdx
- posts/react/react-error-handling.mdx
> [fix] blank 제거

- src/_pages/post/post.page.tsx
- src/shared/common-ui/mdx/mdx-remote.tsx
- src/shared/common-ui/side-toc/side-toc.tsx
- src/shared/common-ui/top-toc/top-toc.tsx
> [feat] post top toc 추가

- app/sitemap.ts
sitemap에 카테고리 페이지가 누락된 부분 수정
sitemap.ts에 카테고리 페이지 추가
> [fix] sitemap category 누락 수정

- src/app/google-addon.tsx
> [fix] addon change

- src/shared/common-ui/side-toc/side-adsense.tsx
- src/shared/common-ui/side-toc/side-toc.tsx
side-toc 하단에 google adsense component 추가
> [feat] google adsense 컴포넌트 추가

- posts/react/react-19rc.mdx
> [feat] React 19 RC 글 업데이트

- posts/html/how-to-make-web-page.mdx
- posts/html/html-layout-tag-and-id-calss-property.mdx
- posts/html/what-is-html.mdx
- 작성했던 mdx 파일 내부의 writeDate & releaseDate 수정
- writeDate와 releaseDate가 큰따옴표로 감싸져있었습니다.
- 변경 사항 1
- 변경 사항 2
- ...
> mod: mdx 파일 writeDate & releaseDate 수정
